// HTML report generator — no external deps, self-contained <style>

export function renderHTMLReport(results, totals) {
  const { passed, warned, failed, skipped, totalTime } = totals;

  const badge = (s) => {
    if (s === 'pass') return '<span class="b pass">PASS</span>';
    if (s === 'warn') return '<span class="b warn">WARN</span>';
    if (s === 'fail') return '<span class="b fail">FAIL</span>';
    if (s === 'skip') return '<span class="b skip">SKIP</span>';
    return '<span class="b">?</span>';
  };

  const rows = results.map(r => {
    const details = r.details ? `<pre>${escapeHtml(r.details)}</pre>` : '';
    const metrics = r.metrics ? Object.entries(r.metrics).map(([k, v]) => `<code>${k}=${v}</code>`).join(' ') : '';
    return `
      <details class="row ${r.status}">
        <summary>
          ${badge(r.status)}
          <strong>${r.label}</strong>
          <span class="msg">${escapeHtml(r.message || '')}</span>
          <span class="time">${(r.duration / 1000).toFixed(1)}s</span>
        </summary>
        <div class="body">
          ${metrics ? `<div class="metrics">${metrics}</div>` : ''}
          ${details}
        </div>
      </details>`;
  }).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Lokizio Audit Report</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  body { font-family: -apple-system, Segoe UI, Arial, sans-serif; background: #0f0f1a; color: #f0f0f5; margin: 0; padding: 24px; }
  h1 { margin: 0 0 8px; }
  .summary { color: #9ca3af; margin-bottom: 24px; font-size: 14px; }
  .totals { display: flex; gap: 12px; margin-bottom: 24px; }
  .tot { padding: 8px 14px; border-radius: 8px; font-weight: 600; font-size: 13px; }
  .tot.pass { background: rgba(52,211,153,0.15); color: #34d399; }
  .tot.warn { background: rgba(251,191,36,0.15); color: #fbbf24; }
  .tot.fail { background: rgba(248,113,113,0.15); color: #f87171; }
  .tot.skip { background: rgba(156,163,175,0.12); color: #9ca3af; }
  .row { border: 1px solid rgba(255,255,255,0.08); border-radius: 10px; margin-bottom: 10px; background: #1a1a2e; overflow: hidden; }
  .row summary { padding: 12px 16px; cursor: pointer; display: flex; align-items: center; gap: 12px; user-select: none; }
  .row summary:hover { background: rgba(255,255,255,0.03); }
  .row .msg { flex: 1; color: #cbd5e1; font-size: 13px; }
  .row .time { color: #64748b; font-size: 12px; }
  .row .body { padding: 12px 16px 16px; border-top: 1px solid rgba(255,255,255,0.05); }
  .metrics { margin-bottom: 10px; color: #94a3b8; font-size: 12px; }
  .metrics code { background: rgba(255,255,255,0.05); padding: 2px 6px; border-radius: 4px; margin-right: 6px; }
  pre { background: #0a0a14; padding: 12px; border-radius: 6px; overflow-x: auto; color: #cbd5e1; font-size: 12px; margin: 0; white-space: pre-wrap; word-break: break-all; }
  .b { padding: 3px 8px; border-radius: 4px; font-size: 11px; font-weight: 700; letter-spacing: 0.5px; }
  .b.pass { background: #34d399; color: #064e3b; }
  .b.warn { background: #fbbf24; color: #78350f; }
  .b.fail { background: #f87171; color: #7f1d1d; }
  .b.skip { background: #64748b; color: #f0f0f5; }
  footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid rgba(255,255,255,0.06); color: #64748b; font-size: 12px; text-align: center; }
</style>
</head>
<body>
  <h1>&#128204; Lokizio Audit</h1>
  <div class="summary">Generated ${new Date().toISOString()} — ${totalTime}s</div>
  <div class="totals">
    ${passed ? `<span class="tot pass">${passed} passed</span>` : ''}
    ${warned ? `<span class="tot warn">${warned} warnings</span>` : ''}
    ${failed ? `<span class="tot fail">${failed} failed</span>` : ''}
    ${skipped ? `<span class="tot skip">${skipped} skipped</span>` : ''}
  </div>
  ${rows}
  <footer>npm run audit &middot; generated by scripts/audit.js</footer>
</body>
</html>`;
}

function escapeHtml(s) {
  if (s == null) return '';
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
