// One-shot script: split i18n.js (2363 lines, 6 languages bundled in const I18N)
// into individual files i18n/<lang>.js so we can lazy-load only the active language.
//
// Usage: node scripts/split-i18n.js

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
// Prefer .original (pristine 6-language bundle) over the current i18n.js (which
// may already be the small loader).
const original = path.join(root, 'i18n.js.original');
const fallback = path.join(root, 'i18n.js');
const source = fs.existsSync(original) ? original : fallback;
console.log('Reading from:', source);
const outDir = path.join(root, 'i18n');

if (!fs.existsSync(outDir)) fs.mkdirSync(outDir);

const src = fs.readFileSync(source, 'utf8');
const lines = src.split('\n');

// Find the start of each language block: `  fr: {`, `  en: {`, etc.
const LANGS = ['fr', 'en', 'es', 'pt', 'it', 'de'];
const starts = {};
for (let i = 0; i < lines.length; i++) {
  for (const lang of LANGS) {
    const re = new RegExp(`^\\s+${lang}:\\s*\\{`);
    if (re.test(lines[i])) {
      starts[lang] = i;
      break;
    }
  }
}

console.log('Detected language start lines:', starts);

// Each block ends at: the line BEFORE the next language's start, or at the closing brace + line "}" + ";" of I18N
const ordered = LANGS.filter(l => starts[l] !== undefined).sort((a, b) => starts[a] - starts[b]);
const ends = {};
for (let i = 0; i < ordered.length; i++) {
  const lang = ordered[i];
  const next = ordered[i + 1];
  if (next) {
    ends[lang] = starts[next] - 1;
  } else {
    // Last language — find the closing `};` of I18N
    for (let j = starts[lang]; j < lines.length; j++) {
      if (/^\};?/.test(lines[j])) { ends[lang] = j - 1; break; }
    }
  }
}

console.log('Detected language end lines:', ends);

// Extract each language block + write a standalone file
for (const lang of ordered) {
  const startLine = starts[lang];
  const endLine = ends[lang];
  // We extract from line after `  fr: {` to line before the closing `}` of the block.
  // Block looks like:
  //   fr: {
  //     'key': 'value',
  //     ...
  //   },
  // We want to keep the inner content + wrap it as { ... }
  // Walk back from endLine to find the actual `  },` (or `  }`) that closes this language block.
  // For middle languages, endLine is `next.start - 1` which often falls on a blank line or comment
  // AFTER the closing `},`. We need to trim everything after (and including) that `},`.
  let realEnd = endLine;
  for (let j = endLine; j > startLine; j--) {
    if (/^\s*\},?\s*$/.test(lines[j])) {
      realEnd = j - 1;
      break;
    }
  }
  const inner = lines.slice(startLine + 1, realEnd + 1).join('\n');
  const trimmedInner = inner;

  const fileContent = `// Auto-generated by scripts/split-i18n.js — do not edit manually.
// Strings for "${lang}" language. Loaded on demand by i18n-loader.js.
window.I18N = window.I18N || {};
window.I18N.${lang} = {
${trimmedInner}
};
// Notify the loader so it can apply translations as soon as this file lands.
if (typeof window.__onI18nLangLoaded === 'function') {
  try { window.__onI18nLangLoaded('${lang}'); } catch (_) {}
}
`;

  const outPath = path.join(outDir, `${lang}.js`);
  fs.writeFileSync(outPath, fileContent);
  const sizeKB = (fs.statSync(outPath).size / 1024).toFixed(1);
  console.log(`  → wrote i18n/${lang}.js (${sizeKB} KB)`);
}

console.log('\nDone. Now update i18n.js to be a small loader that imports only the active language.');
